language: python
python:
  - "2.7"
# setup anaconda

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.0.0-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

# install  packages
install:
  - conda update --yes conda
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes numpy scipy pandas requests flask pyyaml traits networkx dateutil
  - pip install -q python-coveralls --use-mirrors
  - pip install -q nose-cov --use-mirrors
  - pip install -q https://github.com/RDFLib/rdflib/archive/master.zip
  - pip install -q https://github.com/trungdong/prov/archive/rdf.zip
  - pip install -q https://github.com/nipy/nipype/archive/master.zip
  - pip install -q https://github.com/nipy/nibabel/archive/master.zip
  - pip install -q celery
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-doctest --with-cov --cov niquery --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
