---
# Playbook for redis role

- name: Install redis
  apt: pkg=redis-server state=present

# Task queue libraries

- name: Install celery distributed queue library
  sudo: False
  pip: name=celery[redis] state=present executable={{ anaconda_home }}/bin/pip

- name: Install flower for monitoring celery queues
  sudo: False
  pip: name=https://github.com/mher/flower/archive/master.zip state=present executable={{ anaconda_home }}/bin/pip

- name: Ensure flower log directory exists
  file: dest=/var/log/flower state=directory

- name: include supervisor.ini for flower app
  template: src=supervisor.ini.j2 dest=/etc/supervisor/flower.ini
  notify: restart supervisord