---
# Tasks for niquery role

- name: Install dateutil flask ipython pip requests
  sudo: False 
  shell: $HOME/miniconda/bin/conda install --yes -q {{ item }} executable=/bin/bash
  with_items:
    - dateutil 
    - flask 
    - ipython 
    - pip 
    - requests 

# Web application configuration

- name: Copy niquery app into /srv directory
  shell: /bin/cp -r /vagrant/{{ app_name }} {{ webapps_dir }}/{{ app_name }}

- name: Install gunicorn for deploying niquery behind nginx
  sudo: False
  pip: name=https://github.com/benoitc/gunicorn/archive/master.zip state=present executable={{ anaconda_home }}/bin/pip
  
- name: include supervisor.ini for niquery app
  template: src=supervisor.ini.j2 dest=/etc/supervisor/niquery.ini
  notify: restart supervisord

- name: Install flask-restful extension for building a restful api
  sudo: False
  pip: name=https://github.com/twilio/flask-restful/archive/master.zip state=present executable={{ anaconda_home }}/bin/pip


# Semantic Web libraries

- name: Install rdflib library for managing rdf data
  sudo: False
  pip: name=https://github.com/RDFLib/rdflib/archive/master.zip state=present executable={{ anaconda_home }}/bin/pip

- name: Install rdflib-jsonld extension for managing json-ld data
  sudo: False
  pip: name=https://github.com/RDFLib/rdflib-jsonld/archive/master.zip state=present executable={{ anaconda_home }}/bin/pip

- name: Install pyld library for converting json-ld
  sudo: False
  pip: name=https://github.com/digitalbazaar/pyld/archive/master.zip state=present executable={{ anaconda_home }}/bin/pip

- name: Install prov library branch that supports rdf
  sudo: False
  pip: name=https://github.com/satra/prov/archive/enh/rdf.zip state=present executable={{ anaconda_home }}/bin/pip