---
# Tasks for supervisor role

- name: Install supervisor for managing processes
  pip: name=supervisor https://github.com/Supervisor/supervisor/archive/master.zip state=present

- name: Create supervisord config folder
  file: dest=/etc/supervisor state=directory owner=root

- name: Create supervisord config
  copy: src=supervisord.conf dest=/etc/supervisord.conf

- name: Create supervisord init script
  copy: src=supervisord.sh dest=/etc/init.d/supervisord mode=0755 

- name: Link supervisord script
  file: src={{ anaconda_home }}/bin/supervisord dest=/usr/local/bin/supervisord state=link

- name: Link supervisorctl script
  file: src={{ anaconda_home }}/bin/supervisorctl dest=/usr/local/bin/supervisorctl state=link

- name: Start supervisord service and have it run during system startup
  service: name=supervisord state=started enabled=yes